---

- name: "checking for '{{ valet_sh_filename }}' file in '{{ valet_current_path }}'"
  stat:
    path: "{{ valet_current_path }}/{{ valet_sh_filename }}"
  register: valet_sh_file_obj

- name: "fail when '{{ valet_sh_filename }}' file does not exist"
  fail:
    msg: "'{{ valet_sh_filename }}' does not exist in your project folder"
  when: not valet_sh_file_obj.stat.exists

- name: "include variables from '{{ valet_sh_filename }}' file"
  include_vars:
    file: "{{ valet_current_path }}/{{ valet_sh_filename }}"
    name: valet_sh_project_vars

