---

- include_tasks: partials/check-db-name-var.yml

- name: "override 'valet_db_name' variable if db name argument was given"
  set_fact:
    valet_db_name: "{{ valet_arg1 }}"
  when: valet_arg1 | length > 0

- name: "@vsh dropping database '{{ valet_db_name }}'"
  debug:

- name: "drop database '{{ valet_db_name }}'"
  mysql_db:
    name: "{{ valet_db_name }}"
    state: absent
