---

- include_tasks: partials/check-db-name-var.yml

- name: "override 'valet_db_name' variable if db name argument was given"
  set_fact:
    valet_db_name: "{{ valet_arg2 }}"
  when: valet_arg2 | length > 0

- name: fail when no filename was given
  fail:
    msg: "no filename was given"
  when: valet_arg1 | length == 0

- name: set filename from args
  set_fact:
    valet_db_filename: "{{ valet_arg1 }}"

- set_fact:
    valet_db_file: "{{ valet_db_filename }}"
  when: valet_db_filename[0]  == "/"

- set_fact:
    valet_db_file: "{{ valet_current_path }}/{{ valet_db_filename }}"
  when: valet_db_file is not defined

- name: "@vsh starting import of '{{ valet_db_file }}' into '{{ valet_db_name }}'"
  debug:

- name: "@vsh Import database {{ valet_db_file }} into database '{{ valet_db_name }}'"
  mysql_db:
    state: import
    name: "{{ valet_db_name }}"
    target: "{{ valet_db_file }}"

- name: "@vsh import has successfully finished"
  debug: