---

- name: get list of mysql databases
  shell: "mysql -B --disable-column-names --execute 'show databases'"
  register: mysql_query_show_databases_obj

- set_fact:
    valet_current_databases: "{{ mysql_query_show_databases_obj.stdout_lines | difference(valet_mysql_db_blacklist) }}"

- set_fact:
    valet_list: []

- set_fact:
    valet_list: "{{ valet_list + [[ item ]] }}"
  with_items: "{{ valet_current_databases }}"

- vsh-table:
    headers: ['Datebase name']
    rows: "{{ valet_list }}"
