##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: provide power saving settings - systemd service file
  template:
    src: valet-sh-power-saving-settings.service.j2
    dest: "/etc/systemd/system/valet-sh-power-saving-settings.service"
    owner: root
    group: root
    mode: '0755'
  become: true


- name: provide power saving settings - systemd sleep file
  template:
    src: valet-sh-power-saving-settings.j2
    dest: "/lib/systemd/system-sleep/valet-sh-power-saving-settings"
    owner: root
    group: root
    mode: '0755'
  become: true

- name: trigger systemd to reread configs
  systemd:
    daemon_reload: yes

- name: enable power saving settings service
  systemd:
    name: valet-sh-power-saving-settings.service
    state: started
    enabled: yes