##
#   Copyright 2023 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "gather package facts"
  package_facts:
    manager: "auto"

- name: "set default value if npm is installed from repo"
  set_fact:
    nodejs_npm_is_installed_from_repo: false

- name: "check if npm is installed from repo"
  set_fact:
    nodejs_npm_is_installed_from_repo: true
  when: "'npm' in ansible_facts.packages"

- name: "ensure 'gulp' and 'n' is not installed globally"
  npm:
    name: "{{ nvm_uninstall_global_packages_item }}"
    global: yes
    state: absent
  with_items:
    - "n"
    - "gulp"
  loop_control:
    loop_var: nvm_uninstall_global_packages_item
  when: nodejs_npm_is_installed_from_repo

- name: ensure nodejs and npm is not installed
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - nodejs
      - npm
  become: true

- name: check if .zshrc exists in home directory
  stat:
    path: "{{ current_home }}/.zshrc"
  register: zsh_rc_file_obj

- name: "ensure nvm blockinfile is removed from '{{ current_home }}/.zshrc'"
  blockinfile:
    path: "{{ current_home }}/.zshrc"
    state: absent
    block: |
      export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  when: zsh_rc_file_obj.stat.exists

- include_tasks: macos/nvm.yml
  when: valet_sh_config.default_nvm is not defined or valet_sh_config.default_nvm != "volta"

- include_tasks: macos/volta.yml
  when:
    - valet_sh_config.default_nvm is defined
    - valet_sh_config.default_nvm == "volta"

