sudo: false
language: bash
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    - debian-sid
    packages:
    - shellcheck
    - bats
    - bc
script:
  - shellcheck valet.sh
  - MAIN_FUNCTION="run_tests" ./valet.sh