pool:
  vmImage: 'macOS 10.13'

steps:
  - bash: |
      brew update-reset /usr/local/Homebrew
      brew install shellcheck
      shellcheck valet.sh
      tests/test_functions.bats
    displayName: Tests
    failOnStderr: true