---
# roles:
  # Install a role from Ansible Galaxy.
  # - name: valet-sh.nginx
  #  version: 1.2.3

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.general
    version: 1.3.2