---

- name: service | mysql | started
  shell: "launchctl load -w {{ launch_daemons_base_path }}/{{ package.config.startup_script | basename }}"
  become: true

- name: service | mysql | stopped
  shell: "launchctl unload -w {{ launch_daemons_base_path }}/{{ package.config.startup_script | basename }}"
  become: true

- name: service | mysql | restarted
  shell: "launchctl unload -w {{ launch_daemons_base_path }}/{{ package.config.startup_script | basename }} && launchctl load -w {{ launch_daemons_base_path }}/{{ package.config.startup_script | basename }}"
  become: true
