---

- name: fail when dnsmasq_domain is not set
  fail:
    msg: "'dnsmasq_domain' var is not set"
  when: dnsmasq_domain is not defined

- include_tasks: add-domain.yml
  when: (configure_action is defined) and (configure_action == "add")

- include_tasks: delete-domain.yml
  when: (configure_action is defined) and (configure_action == "delete")

