valet_sh_service_rabbitmq_user: admin
valet_sh_service_rabbitmq_password: admin


valet_sh_service_mysql_charset: utf8
valet_sh_service_mysql_collation_string_mysql80: 'SET default_collation_for_utf8mb4 = "utf8mb4_general_ci";'

valet_sh_service_mysql_host_presets:
  mysql57: "127.0.0.1:3307"
  mysql80: "127.0.0.1:3308"
  mariadb104: "127.0.0.1:3317"
  mariadb106: "127.0.0.1:3319"