---

- name: systemd | mailhog | started
  systemd:
    daemon_reload: yes
    name: mailhog
    state: started
  become: true

- name: systemd | mailhog | stopped
  systemd:
    daemon_reload: yes
    name: mailhog
    state: stopped
  become: true

- name: systemd | mailhog | restarted
  systemd:
    daemon_reload: yes
    name: mailhog
    state: restarted
  become: true

- name: brew | mailhog | stopped
  shell: brew services stop mailhog

- name: brew | mailhog | started
  shell: brew services start mailhog

- name: brew | mailhog | restart
  shell: brew services restart mailhog