---

- name: systemd | elasticsearch1 | started
  systemd:
    daemon_reload: yes
    name: elasticsearch1
    state: started
  become: true

- name: systemd | elasticsearch1 | stopped
  systemd:
    daemon_reload: yes
    name: elasticsearch1
    state: stopped
  become: true

- name: systemd | elasticsearch1 | restarted
  systemd:
    daemon_reload: yes
    name: elasticsearch1
    state: restarted
  become: true

- name: systemd | elasticsearch1 | reloaded
  systemd:
    daemon_reload: yes
    name: elasticsearch1
    state: restarted
  become: true

- name: systemd | elasticsearch2 | started
  systemd:
    daemon_reload: yes
    name: elasticsearch2
    state: started
  become: true

- name: systemd | elasticsearch2 | stopped
  systemd:
    daemon_reload: yes
    name: elasticsearch2
    state: stopped
  become: true

- name: systemd | elasticsearch2 | restarted
  systemd:
    daemon_reload: yes
    name: elasticsearch2
    state: restarted
  become: true

- name: systemd | elasticsearch2 | reloaded
  systemd:
    daemon_reload: yes
    name: elasticsearch2
    state: restarted
  become: true

- name: systemd | elasticsearch5 | started
  systemd:
    daemon_reload: yes
    name: elasticsearch5
    state: started
  become: true

- name: systemd | elasticsearch5 | stopped
  systemd:
    daemon_reload: yes
    name: elasticsearch5
    state: stopped
  become: true

- name: systemd | elasticsearch5 | restarted
  systemd:
    daemon_reload: yes
    name: elasticsearch5
    state: restarted
  become: true

- name: systemd | elasticsearch5 | reloaded
  systemd:
    daemon_reload: yes
    name: elasticsearch5
    state: restarted
  become: true


- name: systemd | elasticsearch6 | started
  systemd:
    daemon_reload: yes
    name: elasticsearch6
    state: started
  become: true

- name: systemd | elasticsearch6 | stopped
  systemd:
    daemon_reload: yes
    name: elasticsearch6
    state: stopped
  become: true

- name: systemd | elasticsearch6 | restarted
  systemd:
    daemon_reload: yes
    name: elasticsearch6
    state: restarted
  become: true

- name: systemd | elasticsearch6 | reloaded
  systemd:
    daemon_reload: yes
    name: elasticsearch6
    state: restarted
  become: true

- name: systemd | elasticsearch7 | started
  systemd:
    daemon_reload: yes
    name: elasticsearch7
    state: started
  become: true

- name: systemd | elasticsearch7 | stopped
  systemd:
    daemon_reload: yes
    name: elasticsearch7
    state: stopped
  become: true

- name: systemd | elasticsearch7 | restarted
  systemd:
    daemon_reload: yes
    name: elasticsearch7
    state: restarted
  become: true

- name: systemd | elasticsearch7 | reloaded
  systemd:
    daemon_reload: yes
    name: elasticsearch7
    state: restarted
  become: true