##
# Copyright (c) 2019 TechDivision GmbH
# All rights reserved
#
# This product includes proprietary software developed at TechDivision GmbH, Germany
# For more information see http://www.techdivision.com/
#
# To obtain a valid license for using this software please contact us at
# license@techdivision.com
##
---

xps_model: ""

supported_models:
  - XPS 15 9560
  - XPS 15 9570
  - XPS 15 7590
  - XPS 13 9370
  - XPS 13 9380

basic_packages:
  - powertop
  - lm-sensors
  - vim
  - less
  - rsync
  - curl
  - wget
  - htop
  - iotop
  - aptitude
#  - python-mysqldb
  - git
  - sudo
  - unzip
  - rsyslog
  - acl
  - apt-transport-https
  - screen
  - hdparm
  - smartmontools
  - net-tools
  - traceroute
  - network-manager-openvpn
  - network-manager-openvpn-gnome

additional_packages:
  - ukuu

absent_packages:
  - ubuntu-web-launchers
