##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: Check if npm is installed
  shell: command -v nvm >/dev/null 2>&1
  register: nvm_installed_obj
  ignore_errors: yes

- name: "ensure 'gulp' and 'n' is not installed globally"
  npm:
    name: "{{ item }}"
    global: yes
    state: absent
  become: true
  with_items:
    - "n"
    - "gulp"
  when: nvm_installed_obj.rc == 0

- name: "ensure 'nvm' is installed"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ current_home }}/.nvm/nvm.sh"
  register: nvm_installation_obj

- name: check if .zshrc exists in home directory
  stat:
    path: "{{ current_home }}/.zshrc"
  register: zsh_rc_file_obj

- name: ensure nvm will be loaded with zsh
  blockinfile:
    path: "{{ current_home }}/.zshrc"
    block: |
      export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  when: zsh_rc_file_obj.stat.exists

- name: "install default node version"
  shell: "nvm install {{ node_version }}"
  when: nvm_installation_obj.changed

- name: "install default node version"
  shell: "nvm alias default {{ node_version }}"
  when: nvm_installation_obj.changed