---

- name: "ensure 'gulp' and 'n' is not installed globally"
  npm:
    name: "{{ item }}"
    global: yes
    state: absent
  become: true
  with_items:
    - "n"
    - "gulp"

- name: "ensure 'nvm' is installed"
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
  args:
    creates: "{{ current_home }}/.nvm/nvm.sh"
  register: nvm_installation_obj

- name: check if .zshrc exists in home directory
  stat:
    path: "{{ current_home }}/.zshrc"
  register: zsh_rc_file_obj

- name: ensure nvm will be loaded with zsh
  blockinfile:
    path: "{{ current_home }}/.zshrc"
    block: |
      export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
  when: zsh_rc_file_obj.stat.exists

- name: "install default node version"
  shell: "nvm install {{ node_version }}"
  when: nvm_installation_obj.changed

- name: "install default node version"
  shell: "nvm alias default {{ node_version }}"
  when: nvm_installation_obj.changed