- name: "workflows » aem » project-setup | remove old installations"
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ author_dir }}"
    - "{{ publish_dir }}"
    - "{{ runtime_tmp_dir }}"
    #@TODO add dispatcher

- name: "workflows » aem » project-setup | ensure local cache directory '{{ valet_sh_aem_local_cache_dir }}' exists"
  file:
    path: "{{ valet_sh_aem_local_cache_dir }}"
    state: directory

- name: "workflows » aem » project-setup | create runtime directory structure"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ runtime_dir }}"
    - "{{ author_dir }}"
    - "{{ publish_dir }}"
    - "{{ dispatcher_dir }}"
    - "{{ runtime_tmp_dir }}"
