---

- name: uninstall useless packages
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - ubuntu-web-launchers
  become: true

# Add powertop, lm-sensors, vim + common packerl