##
# Copyright (c) 2019 TechDivision GmbH
# All rights reserved
#
# This product includes proprietary software developed at TechDivision GmbH, Germany
# For more information see http://www.techdivision.com/
#
# To obtain a valid license for using this software please contact us at
# license@techdivision.com
##
---

- include_tasks: system.yml

- include_tasks: basics.yml



