##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: systemd | nginx | started
  systemd:
    daemon_reload: yes
    name: nginx
    state: started
  become: true

- name: systemd | nginx | stopped
  systemd:
    daemon_reload: yes
    name: nginx
    state: stopped
  become: true

- name: systemd | nginx | restarted
  systemd:
    daemon_reload: yes
    name: nginx
    state: restarted
  become: true

- name: systemd | nginx | reloaded
  systemd:
    daemon_reload: yes
    name: nginx
    state: reloaded
  become: true

- name: "systemd | php5.6-fpm | started"
  systemd:
    name: "php5.6-fpm"
    state: started
  become: true

- name: "systemd | php5.6-fpm | stopped"
  systemd:
    name: "php5.6-fpm"
    state: stopped
  become: true

- name: "systemd | php5.6-fpm | restarted"
  systemd:
    name: "php5.6-fpm"
    state: restarted
  become: true

- name: "systemd | php5.6-fpm | reloaded"
  systemd:
    name: "php5.6-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.0-fpm | started"
  systemd:
    name: "php7.0-fpm"
    state: started
  become: true

- name: "systemd | php7.0-fpm | stopped"
  systemd:
    name: "php7.0-fpm"
    state: stopped
  become: true

- name: "systemd | php7.0-fpm | restarted"
  systemd:
    name: "php7.0-fpm"
    state: restarted
  become: true

- name: "systemd | php7.0-fpm | reloaded"
  systemd:
    name: "php7.0-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.1-fpm | started"
  systemd:
    name: "php7.1-fpm"
    state: started
  become: true

- name: "systemd | php7.1-fpm | stopped"
  systemd:
    name: "php7.1-fpm"
    state: stopped
  become: true

- name: "systemd | php7.1-fpm | restarted"
  systemd:
    name: "php7.1-fpm"
    state: restarted
  become: true

- name: "systemd | php7.1-fpm | reloaded"
  systemd:
    name: "php7.1-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.2-fpm | started"
  systemd:
    name: "php7.2-fpm"
    state: started
  become: true

- name: "systemd | php7.2-fpm | stopped"
  systemd:
    name: "php7.2-fpm"
    state: stopped
  become: true

- name: "systemd | php7.2-fpm | restarted"
  systemd:
    name: "php7.2-fpm"
    state: restarted
  become: true

- name: "systemd | php7.2-fpm | reloaded"
  systemd:
    name: "php7.2-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.3-fpm | started"
  systemd:
    name: "php7.3-fpm"
    state: started
  become: true

- name: "systemd | php7.3-fpm | stopped"
  systemd:
    name: "php7.3-fpm"
    state: stopped
  become: true

- name: "systemd | php7.3-fpm | restarted"
  systemd:
    name: "php7.3-fpm"
    state: restarted
  become: true

- name: "systemd | php7.3-fpm | reloaded"
  systemd:
    name: "php7.3-fpm"
    state: reloaded
  become: true

- name: systemd | reload
  systemd:
    daemon_reload: yes
  become: true
