---

- name: load state-manager
  include_role:
    name: state-manager
  vars:
    state_action: get_state
# output: package_condition

- include_tasks: install/main.yml
  when: (package_action is defined) and (package_action == "install")

- include_tasks: upgrade/main.yml
  when: (package_action is defined) and (package_action == "upgrade")
