---

- name: check required vars
  fail:
    msg: "required variable {{ item }} does not exist"
  when: "{{ item }} is not defined"
  with_items:
    - package.name
    - package.version

- include_tasks: prepare.yml

- include_tasks: install.yml
