---

- name: systemd | network-manager | started
  systemd:
    daemon_reload: yes
    name: network-manager
    state: started
  become: true

- name: systemd | network-manager | stopped
  systemd:
    daemon_reload: yes
    name: network-manager
    state: stopped
  become: true

- name: systemd | network-manager | reload
  systemd:
    daemon_reload: yes
    name: network-manager
    state: reloaded
  become: true

- name: systemd | network-manager | restarted
  systemd:
    daemon_reload: yes
    name: network-manager
    state: restarted
  become: true

- name: brew | dnsmasq | restarted
  shell: brew services restart dnsmasq
  become: true

- name: brew | dnsmasq | stopped
  shell: brew services stop dnsmasq
  become: true

- name: brew | dnsmasq | started
  shell: brew services start dnsmasq
  become: true