##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: fail when no xdebug version is set
  fail:
    msg: "no xdebug version set"
  when: current_php.compile_xdebug.version is not defined

- name: "install php-dev and pecl package when required"
  apt:
    name: ["php{{ php_version }}-dev","php-pear", "build-essential"]
    state: present
  become: true

- name: Create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: xdebug_tmp_directory_obj

- name: "download and unpack xdebug sources into tmp directory {{ xdebug_tmp_directory_obj.path }}"
  unarchive:
    src: "https://github.com/xdebug/xdebug/archive/{{ current_php.compile_xdebug.version }}.tar.gz"
    dest: "{{ xdebug_tmp_directory_obj.path }}"
    remote_src: true
    extra_opts: [ --strip-components=1 ]

- name: "run phpize on xdebug module source"
  command: "/usr/bin/phpize{{ php_version }}"
  args:
    chdir: "{{ xdebug_tmp_directory_obj.path }}"

- name: "run ./configure on xdebug module source"
  command: "./configure --with-php-config=/usr/bin/php-config{{ php_version }}"
  args:
    chdir: "{{ xdebug_tmp_directory_obj.path }}"

- name: "run make clean on xdebug module source"
  command: "make clean"
  args:
    chdir: "{{ xdebug_tmp_directory_obj.path }}"

- name: "run make all on xdebug module source"
  command: "make all"
  args:
    chdir: "{{ xdebug_tmp_directory_obj.path }}"

- name: "get php extension dir"
  command: "/usr/bin/php-config{{ php_version }} --extension-dir"
  register: php_extension_dir

- name: "copy xdebug.so extension to extension dir"
  copy:
    src: "{{ xdebug_tmp_directory_obj.path }}/modules/xdebug.so"
    dest: "{{ php_extension_dir.stdout }}/{{ current_php.compile_xdebug.target_module_name | default('xdebug2') }}.so"
  become: true

- name: ensure tmp directory is deleted
  file:
    path: "{{ xdebug_tmp_directory_obj.path }}"
    state: absent
  become: true


