##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "commands » list | set runtime flag"
  set_fact:
    valet_config_in_command: true

- name: "commands » list | include valet etc config file"
  include_vars:
    file: "{{ valet_etc_config_file }}"
    name: valet_etc_config_obj

- name: "commands » list | set empty array 'valet_config_list'"
  set_fact:
    valet_config_list: []

- name: "commands » list | add config to array"
  set_fact:
    valet_config_list: "{{ valet_config_list + [[ item.key, item.value ]] }}"
  with_dict: "{{ valet_etc_config_obj }}"

- name: "commands » list | print table based on 'valet_config_list' array"
  vsh-table:
    headers: ['Key', 'Value']
    rows: "{{ valet_config_list }}"
  tags:
  - skip_ansible_lint