---

- name: set package_base_path
  set_fact:
    package_base_path: "{{ base_path }}/{{ current_package_name }}/{{ current_package_version }}"

- name: set base package variables
  set_fact:
    package_dist_path: "{{ package_base_path }}/dist"
    package_etc_path: "{{ package_base_path }}/etc"
    package_data_path: "{{ package_base_path }}/data"
    package_log_path: "{{ package_base_path }}/log"
    package_tmp_path: "{{ package_base_path }}/tmp"
    package_run_path: "{{ package_base_path }}/run"

- name: set additional variables
  set_fact:
    package_bin_path: "{{ package_dist_path }}/bin"

- name: call install.yml
  include_tasks: install/install.yml

- name: call configure.yml
  include_tasks: install/configure.yml


- name: update state-manager
  include_role:
    name: state-manager
  vars:
    state_action: update_state
    state_package_name: "{{ current_package_name }}"
    state_package_version: "{{ current_package_version }}"