---

- name: Cloning  oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh"
    dest: "{{ current_home }}/.oh-my-zsh"
    force: yes
  register: cloning

- name: Creating new ~/.zshrc
  copy:
    src: "~/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ current_home }}/.zshrc"
    force: no
  when: cloning is changed

- name: load aliases file in .zshrc
  blockinfile:
    path: "{{ current_home }}/.zshrc"
    block: |
      if [ -f ~/.aliases ]; then
          . ~/.aliases
      fi

- name: ensure .profile file exists
  file:
    path: "{{ current_home }}/.profile"
    state: touch

- name: check for .zprofile file in user's home directory
  stat:
    path: "{{ current_home }}/.zprofile"
  register: zsh_zprofile_obj

- name: create .zprofile when not existent
  blockinfile:
    path: "{{ current_home }}/.zprofile"
    block: |
      emulate sh
      . ~/.profile
      emulate zsh
    create: yes
  when: zsh_zprofile_obj.stat.exists == False
