---

- name: "templates » magento1 | check for magento1 project"
  stat:
    path: "{{ valet_current_path }}/app/code/core/Mage"
  register: m1_checker_obj

- name: "templates » magento1 | provide nginx vhost configuration for {{ link_name }}.{{ development_tld }}"
  template:
    src: "nginx/magento1.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/{{ link_name }}.{{ development_tld }}.conf"
    mode: '0644'
  notify: brew | nginx | restarted
  when: m1_checker_obj.stat.exists

- name: "templates » magento1 | set var 'template_found' when m1 instance was found"
  set_fact:
    template_found: true
  when: m1_checker_obj.stat.exists