---

- name: set working dir name
  set_fact:
    valet_working_dir: "{{ valet_current_path | basename }}"

- name: set default db_name var with value of valet_working_dir
  set_fact:
    db_name: "{{ valet_working_dir }}"

- name: override working dir var if separate db name was given
  set_fact:
    db_name: "{{ valet_arg1 }}"
  when: valet_arg1 | length > 0

- name: "drop database {{ valet_arg1 }}"
  mysql_db:
    name: "{{ db_name }}"
    state: absent
