---

- name: set working dir name
  set_fact:
    valet_working_dir: "{{ valet_current_path | basename }}"

- name: fail when no filename was given
  fail:
    msg: "no filename was given"
  when: valet_arg1 | length == 0

- name: set filename from args
  set_fact:
    valet_db_filename: "{{ valet_arg1 }}"

- name: set db_name when arguement is not empty
  set_fact:
    valet_db_name: "{{ valet_arg2 }}"
  when: valet_arg2 | length > 0

- name: build valet_db_name var
  set_fact:
    valet_db_name: "{{ valet_working_dir }}"
  when: valet_db_name is not defined

- set_fact:
    valet_db_file: "{{ valet_db_filename }}"
  when: valet_db_filename[0]  == "/"

- set_fact:
    valet_db_file: "{{ valet_current_path }}/{{ valet_db_filename }}"
  when: valet_db_file is not defined

- name: "Dump database {{ valet_db_name }} into {{ valet_current_path }}/{{ valet_db_filename }}"
  mysql_db:
    state: import
    name: "{{ valet_db_name }}"
    target: "{{ valet_db_file }}"
