##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: set working dir name
  set_fact:
    valet_working_dir: "{{ valet_current_path | basename }}"

- name: set default db_name var with value of valet_working_dir
  set_fact:
    db_name: "{{ valet_working_dir }}"

- name: override working dir var if separate db name was given
  set_fact:
    db_name: "{{ valet_arg1 }}"
  when: valet_arg1 | length > 0

- name: "drop database {{ valet_arg1 }}"
  mysql_db:
    name: "{{ db_name }}"
    state: absent

- name: "create database {{ valet_arg1 }}"
  mysql_db:
    name: "{{ db_name }}"
    encoding: "utf8"
    state: present