---

- name: "prepare || ensure package directories existing"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ package_user }}"
    group: "{{ package_group }}"
    mode: "0755"
  become: true
  with_items:
    - "{{ package_manager_tmp_dir }}"
    - "{{ package_base_dir }}"
    - "{{ package_etc_dir }}"
    - "{{ package_run_dir }}"
    - "{{ package_log_dir }}"

- tempfile:
    state: file
    suffix: temp
  register: package_yml_file_object

- set_fact:
    package_yml_file: "{{ package_yml_file_object.path }}"

- set_fact:
    package_yml_url: "{{ distil_base_url }}/{{ os_version }}/{{ package_channel }}/package.yml"

- get_url:
    url: "{{ package_yml_url }}"
    dest: "{{ package_yml_file }}"
    force: true
  register: package_yml_download_obj

- name: read package yml
  include_vars:
    file: "{{ package_yml_file }}"

- set_fact:
    package_candidate: "{{ package }}"

- set_fact:
    package_candidate: "{{ package_candidate|combine({'id':\"{{ package.name }}-{{ package.version}}\"}) }}"

- set_fact:
    package_channel_info: "{{ packages[package_candidate.id] | default ('undefined') }}"

- fail:
    msg: "Package {{ package_candidate.id }} not available in channel {{ package_channel }}"
  when: package_channel_info is undefined

- set_fact:
    package_candidate: "{{ package_candidate|combine({'base_dir':package_base_dir}) }}"

- set_fact:
    package_candidate: "{{ package_channel_info|combine(package_candidate,{'url':\"{{ distil_base_url }}/{{ os_version }}/{{ package_channel }}/{{ package.name }}/{{ package.version }}/{{ package_channel_info.filename }}\"}) }}"

- set_fact:
    package_candidate: "{{ package_candidate }}"

