##
# Copyright (c) 2019 TechDivision GmbH
# All rights reserved
#
# This product includes proprietary software developed at TechDivision GmbH, Germany
# For more information see http://www.techdivision.com/
#
# To obtain a valid license for using this software please contact us at
# license@techdivision.com
##
---

- name: Uninstall useless packages
  apt:
    name: "{{ absent_packages }}"
    state: absent
  become: true

- name: Install common basic_packages
  apt:
    name: "{{ basic_packages }}"
    state: present
  become: true
