##
# Copyright (c) 2019 TechDivision GmbH
# All rights reserved
#
# This product includes proprietary software developed at TechDivision GmbH, Germany
# For more information see http://www.techdivision.com/
#
# To obtain a valid license for using this software please contact us at
# license@techdivision.com
##
---

- name: Get current XPS model (was not defined manually)
  shell: |
    dmidecode -t 1 | grep 'Product Name:' | awk -F ': ' '{print $2}'
  become: true
  register: xps_model_result
  when: (xps_model is not defined) or
    (xps_model == "")
  changed_when: false

- name: Set current XPS model
  set_fact:
    xps_model: "{{ xps_model_result.stdout }}"
  when: (xps_model is not defined) or
    (xps_model == "")

- name: Fail when XPS model is not supported
  fail:
    msg: "Your XPS model is not yet supported"
  when: (xps_model is not defined) or
    (xps_model == "") or
    (xps_model not in supported_models)

#-  debug:
#    var: xps_model

- include_tasks: basics.yml

#- include_tasks: system.yml
- include_tasks: "{{ xps_model |replace(' ', '-') }}.yml"

