##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "fail when os is not ubuntu 20.04"
  fail:
    msg: "only Ubuntu 20.04 is supported for XPS15 9500!"
  when: ansible_distribution_release != "focial"

- name: ensure universe repository is enabled
  shell: "add-apt-repository -y universe"
  become: true

- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  become: true

- name: install power management packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - thermald
      - powertop
  become: true

- name: ensure tlp packages are not installed
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - tlp
      - tlp-rdw
  become: true

- name: ensure tpl config does not exist
  file:
    path: "{{ item }}"
    state: absent
  become: true
  with_items:
    - /etc/tlp.conf
    - /etc/default/tlp
    - /etc/tlp.d

- name: "enable graphic drivers ppa"
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution_release == "bionic"

- name: "disable graphic drivers ppa"
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    update_cache: yes
    state: absent
  become: true
  when: ansible_distribution_release != "bionic"

- name: "run ubuntu-drivers autoinstall"
  shell: "ubuntu-drivers autoinstall"
  become: true

- name: install video codec packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ubuntu-restricted-extras
      - va-driver-all
      - vainfo
      - libva2
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
  become: true

- apt_repository:
    repo: ppa:eh5/pulseaudio-a2dp
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution_release == "bionic"

- apt_repository:
    repo: ppa:eh5/pulseaudio-a2dp
    update_cache: yes
    state: absent
  become: true
  when: ansible_distribution_release != "bionic"

- name: install bluetooth sound codec packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - libavcodec58
      - libldac
      - pulseaudio-modules-bt
  become: true
  when: ansible_distribution_release == "bionic"

- name: install intel microcode updates
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - intel-microcode
  become: true

- name: Enable power saving tweaks for Intel chip
  copy:
    content: 'options i915 enable_fbc=1 enable_guc=3 disable_power_well=0 fastboot=1 enable_psr=0'
    dest: "/etc/modprobe.d/i915.conf"
  become: true

- name: enable fan speed with lm-sensors
  lineinfile:
    path: /etc/modprobe.d/dell-smm-hwmon.conf
    line: 'options dell-smm-hwmon restricted=0 force=1'
    create: true
  become: true

- name: enable dell specific module
  lineinfile:
    path: /etc/modules
    line: 'dell-smm-hwmon'
  become: true

- name: "run update-initramfs -u"
  shell: "update-initramfs -u"
  become: true

- name: "switch to intel gpu"
  shell: "prime-select intel"
  become: true

- include_tasks: "hardware-related/bbswitch.yml"
  when: ansible_distribution_release == "focal"

- name: "ensure backport-iwlwifi-dkms package is NOT installed on focal"
  apt:
    name: "backport-iwlwifi-dkms"
    state: absent
  become: true
  when: ansible_distribution_release == "focal"

- name: update grub config
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_rev_override=1 nouveau.modeset=0 pcie_aspm=force mem_sleep_default=deep"'
  become: true

- name: "run update-grub"
  shell: "update-grub"
  become: true

- name: disable gnome tracker apps
  systemd:
    masked: yes
    name: "{{ item }}"
  with_items:
    - tracker-extract.desktop
    - tracker-miner-apps.desktop
    - tracker-miner-fs.desktop
    - tracker-store.desktop
  become: true

- set_fact:
    systemd_sleep_modulename: "i2c_hid"

- name: provide systemd sleep configuration for touchpad
  template:
    src: systemd-sleep-module.j2
    dest: "/lib/systemd/system-sleep/touchpad"
    owner: root
    group: root
    mode: '0755'
  become: true

- name: install Ubuntu Hardware Enablement Stack
  apt:
    name: "{{ ubuntu_hwe_packages }}"
    state: present
    install_recommends: true
  become: true
  when: ansible_distribution_release == "bionic"
