---

- name: systemd | rabbitmq-server | started
  systemd:
    name: rabbitmq-server
    state: started
  become: true

- name: systemd | rabbitmq-server | stopped
  systemd:
    name: rabbitmq-server
    state: stopped
  become: true

- name: systemd | rabbitmq-server | restarted
  systemd:
    name: rabbitmq-server
    state: restarted
  become: true

- name: systemd | rabbitmq-server | reloaded
  systemd:
    name: rabbitmq-server
    state: reloaded
  become: true

- name: systemd | rabbitmq-server | full-restart
  systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes
  become: true

- name: brew | rabbitmq | started
  shell: brew services start rabbitmq

- name: brew | rabbitmq | stopped
  shell: brew services stop rabbitmq

- name: brew | rabbitmq | restarted
  shell: brew services restart rabbitmq

