---

- name: install common packages
  apt:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
     - git

- name: set max_map_count on host to 262144
  sysctl:
    name: vm.max_map_count
    value: "262144"
    state: present
  become: true

