---

- name: "ensure mailhog is installed"
  homebrew:
    name: mailhog
    state: present
  notify: brew | mailhog | restart

- name: "generate ssl-certificate for {{ cert_prefix }}"
  include_role:
    name: certificate
    public: true
  vars:
    cert_prefix: mailhog

- name: provide init script for mailhog
  template:
    src: "mailhog.conf.j2"
    dest: "{{ valet_sh_prefix }}/etc/nginx/conf.d/mailhog.conf"
    mode: '0644'
  notify: brew | nginx | restarted
  become: true