---

#####################
- name: get path of composer binary
  shell: "which composer"
  register: composer_bin_obj

- name: set composer_bin variable
  set_fact:
    composer_bin: "{{ composer_bin_obj.stdout }}"


############################
- name: "set default php binary name"
  set_fact:
    php_bin_name: "php"

- name: add suffix to php binary when configured in valet-sh.yml
  set_fact:
    php_bin_name: "php{{ valet_sh_project_vars.services.php.version }}"
  when:
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.php is defined
    - valet_sh_project_vars.services.php.version is defined

- name: get path of php binary
  shell: "which {{ php_bin_name }}"
  register: php_bin_obj

- fail:
    msg: "could not find php binary '{{ php_bin_name }}'"
  when: php_bin_obj.stdout | length == 0

- name: set php_bin variable
  set_fact:
    php_bin: "{{ php_bin_obj.stdout }}"


######################
- name: set default path to project source
  set_fact:
    valet_sh_project_src_path: "{{ valet_current_path }}"

- name: set path to project source
  set_fact:
    valet_sh_project_src_path: "{{ valet_current_path }}/{{ valet_sh_project_vars.instance.path }}"
  when:
    - valet_sh_project_vars.instance is defined
    - valet_sh_project_vars.instance.path is defined


######################

- name: set default node version
  set_fact:
    valet_sh_node_version: "{{ valet_sh_default_node_version }}"

- name: override node version based on .valet-sh.yml
  set_fact:
    valet_sh_node_version: "{{ valet_sh_project_vars.services.node.version }}"
  when:
    - valet_sh_project_vars.services is defined
    - valet_sh_project_vars.services.node is defined
    - valet_sh_project_vars.services.node.version is defined
