##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "workflows » magento2 » project-install | run composer install in current dir"
  command: "{{ php_bin }} {{ composer_bin_obj.stdout }} install"
  args:
    chdir: "{{ valet_current_path }}"
    removes: "composer.json"

- name: "workflows » magento2 » project-install | run composer install in project source path when defined in .valet-sh.yml"
  command: "{{ php_bin }} {{ composer_bin_obj.stdout }} install"
  args:
    chdir: "{{ valet_sh_project_src_path }}"
    removes: "composer.json"
  when: valet_current_path != valet_sh_project_src_path

- name: "workflows » magento2 » project-install | switch node version to '{{ valet_sh_node_version }}'"
  command: "n {{ valet_sh_node_version }}" # noqa 301
  args:
    chdir: "{{ valet_current_path }}"
  become: true

- name: "workflows » magento2 » project-install | run npm install in current dir"
  command: "npm install"
  args:
    chdir: "{{ valet_current_path }}"
    removes: "packages.json"
  with_first_found:
    - /usr/local/bin/npm
    - /usr/bin/npm

- name: "workflows » magento2 » project-install | run npm install in project source path when defined in .valet-sh.yml"
  command: "npm install"
  args:
    chdir: "{{ valet_sh_project_src_path }}"
    removes: "packages.json"
  when: valet_current_path != valet_sh_project_src_path
  with_first_found:
    - /usr/local/bin/npm
    - /usr/bin/npm
