---

- set_fact:
    package:
      name: "mysql"
      version: "5.7"
      config:
        startup_script: "sh.valet.mysql57.mysqld.plist"
        templates:
          - source: "mysql57.j2"
            target: "/usr/local/bin/mysql57"
            mode: "0755"
          - source: "mysqldump57.j2"
            target: "/usr/local/bin/mysqldump57"
            mode: "0755"
      post_install:
        include: "install.yml"