---

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: use php ppa (Ubuntu)
  apt_repository:
    repo: 'ppa:ondrej/php'
  when: ansible_distribution == "Ubuntu"
  become: true

- name: add debian sury apt-key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
  when: ansible_distribution == "Debian"
  become: true

- name: use php reposoitpry (Debian)
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
  when: ansible_distribution == "Debian"
  become: true

- name: "install defined php versions"
  include: install-php.yml
    current_php="{{ item }}"
  with_items: "{{ php_multi }}"

- name: "set default php cli version"
  alternatives:
    name: php
    path: "/usr/bin/php{{ item.version }}"
  with_items: "{{ php_multi }}"
  when: (item.default is defined) and (item.default == true)
  become: true