---

- include_tasks: "migrations/main.yml"

- name: ensure apt-transport-https is installed
  apt:
    name: apt-transport-https
    state: present
  become: true

- name: use php ppa (Ubuntu)
  apt_repository:
    repo: 'ppa:ondrej/php'
  become: true

- name: "install defined php versions"
  include: install-php.yml
    current_php="{{ item }}"
  with_items: "{{ php_multi }}"

- name: "set default php cli version"
  alternatives:
    name: php
    path: "/usr/bin/php{{ item.version }}"
  with_items: "{{ php_multi }}"
  when: (item.default is defined) and (item.default == true)
  become: true