##
#   Copyright 2020 TechDivision GmbH
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
##
---

- name: "ensure composer is not installed via homebrew"
  homebrew:
    name: composer
    state: absent

- name: "ensure composer is installed"
  get_url:
    url: https://getcomposer.org/composer-1.phar
    dest: "{{ composer_bin }}"
    owner: "{{ current_user }}"
    group: "{{ current_group }}"
    mode: "0755"
    force: true
  become: true

- name: install prestissimo
  composer:
    command: require
    executable: /usr/local/bin/php7.3
    global_command: yes
    arguments: hirak/prestissimo

- name: "add composer aliases to {{ current_home }}/.aliases"
  lineinfile:
    path: "{{ current_home }}/.aliases"
    line: "alias {{ current_composer_alias.alias }}='{{ current_composer_alias.target }}'"
    create: yes
  with_items: "{{ composer_aliases }}"
  loop_control:
    loop_var: current_composer_alias