---

- name: "ensure composer is installed"
  homebrew:
    name: composer
    state: present

- name: install prestissimo
  composer:
    command: require
    global_command: yes
    arguments: hirak/prestissimo

- name: "add composer aliases to {{ current_home }}/.aliases"
  lineinfile:
    path: "{{ current_home }}/.aliases"
    line: "alias {{ current_composer_alias.alias }}='{{ current_composer_alias.target }}'"
    create: yes
  with_items: "{{ composer_aliases_mac }}"
  loop_control:
    loop_var: current_composer_alias