#
# valet.sh | asd
#
# @author: "Philipp Dittert"
# @command: "asd"
# @platform: macOS Ubuntu
# @description: "run init-instance command | Usage: valet.sh init-instance
# @help: "valet.sh -h db"
# @usage: "valet.sh init-instance

---

- name: "asd"
  hosts: local
  gather_facts: True
  tasks:
    - debug:
        msg: "{{ cli }}"
