#
# valet.sh | db
#
# @author: "Philipp Dittert"
# @command: "db"
# @description: "list, create, drop, reset, import, export a mysql database"
# @usage: "valet.sh db <action>"
# @help:
#
# list: list all databases
# valet.sh db list
#
# create: create a new database
# valet.sh db create <dbname>
#
# drop: drops a existing database
# valet.sh db drop <dbname>
#
# reset: drops and creates a database
# valet.sh db reset <dbname>
#
# import: import a mysql database dump. Database will be created when
#
# TODO
#
#
#
---

- name: "db"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  vars:
    valet_action: "{{ cli.args[0] | default() }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    valet_arg1: "{{ cli.args[1] | default() }}"
    valet_arg2: "{{ cli.args[2] | default() }}"
    valet_arg3: "{{ cli.args[3] | default() }}"
  roles:
    - valet-db