---
#
# valet.sh | install
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "install"
# @description: "Install and configure the default development stack "
# @usage: "valet.sh install"

- name: "install"
  hosts: local
  gather_facts: True
  roles:
    - shared-variables
    - common
    - certificate
    - network-manager
    - elasticsearch
    - zsh
    - nginx
    - redis
    - php
    - nodejs
    - mailhog
    - mysql-server
    - magerun1
    - magerun2
    - rabbitmq
    - composer
    - google-chrome
