---
#
# valet.sh
#
# @author: "Johann Zelger"
# @command: "install"
# @description: "Install command"
# @subcommands: ["all","redis"]

- name: "install"
  hosts: local
  gather_facts: True

  roles:
    - gnutar
    - redis
    - php