#
# valet.sh | install
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "install"
# @description: "Install and configure the default development stack "
# @usage: "valet.sh install"

---

- name: "install"
  hosts: local
  gather_facts: true
  roles:
    - valet-install
