#
# valet.sh | link
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "link"
# @description: "Link current directory with given name | Usage: valet.sh link projectx php72"
# @usage: "valet.sh link <name> <php-version>"
# @help:
#
# EXAMPLES:
#
# link the current folder as projectx and use php7.2
# valet.sh link projectx php7.2
#
---
- name: "link"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  vars:
    valet_action: link
    link_name: "{{ cli.args[0] }}"
    valet_current_path: "{{ lookup('env','OLDPWD') }}"
    php_version: "{{ cli.args[1] | default() }}"
  roles:
    - valet-link
