#
# valet.sh | links
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "links"
# @description: "Show all currently linked sites"
# @usage: "valet.sh links"
# @help:
#
# list all existing linked projects
# valet.sh links
#
---
- name: "links"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  vars:
    valet_action: links
  roles:
    - valet-link