---
#
# valet.sh | link
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "link"
# @description: "Link current directory with given name"
# @usage: "valet.sh link <name>"

- name: "link"
  hosts: local
  gather_facts: True
  vars:
    valet_action: link
    link_name: "{{ cli.args[0] }}"
    link_path: "{{ lookup('env','OLDPWD') }}"
  roles:
    - valet-link