---
#
# valet.sh | purge
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "purge"
# @description: "purge package"
# @usage: "valet.sh purge <package>@<version> <package>@<version> <package>@<version>"

- name: "purge"
  hosts: local
  gather_facts: True

  vars:
    install_default_versions:
      php: "7.2"
      mysql: "5.7"
      redis: "3.2"
      nginx: "1.14"
      elasticsearch: "6"
      rabbitmq: "3.7"
      dnsmasq: "2.8"
      mailhog: "1.0"
    install_default_packages:
      - nginx
      - php
      - mysql
      - redis
      - elasticsearch

  vars_prompt:
    - name: "confirm_purge"
      prompt: "ALL DATA WILL BE DELETED for package. are you sure (yes/no)"

  tasks:

    - include_role:
        name: package-manager
      vars:
        package_action: "purge"
        package_name: "{{ item.split('@')[0] }}"
        package_version: "{{ item.split('@')[1] | default(install_default_versions[item.split('@')[0]]) }}"
      with_items: "{{ cli.args }}"
      when: cli.args | length > 0


    - include_role:
        name: package-manager
      vars:
        package_action: "purge"
        package_name: "{{ item }}"
        package_version: "{{ install_default_versions[item] }}"
      with_items: "{{ install_default_packages }}"
      when: cli.args | length == 0

