---
#
# valet.sh | restart
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "restart"
# @description: "Restart service"
# @usage: "valet.sh restart <package> <version>"

- name: "restart"
  hosts: local
  gather_facts: True

  tasks:

  - fail:
      msg: 'cli argument package not defined'
    when: cli.args.0 is not defined

  - fail:
      msg: 'cli argument version not defined'
    when: cli.args.1 is not defined

  - import_role:
      name: service-manager
    vars:
      service_action: "restart"
      package_name: "{{ cli.args.0 }}"
      package_version: "{{ cli.args.1 }}"
