#
# valet.sh | update-dev-ca
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "update-dev-ca"
# @description: "adds the local development CA to Firefox/Chrome as trusted certificate"
# @usage: "valet.sh update-dev-ca"
# @help:
#
# ensure the development CA is imported into the browser keystore
# valet.sh update-dev-ca
#
---
- name: "update-dev-ca"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  roles:
    - certificate