#
# valet.sh | xdebug
#
# @author: "Johann Zelger"
# @author: "Philipp Dittert"
# @command: "xdebug"
# @description: "enables xdebug for given php version e.g 7.2 7.3 | Usage: xdebug on 7.1"
# @usage: "valet.sh xdebug <state> <php-version>"
# @help:
# tbd...
---
- name: "xdebug"
  hosts: local
  gather_facts: True
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "[sudo] Password"
      private: yes
  vars:
    valet_action: "{{ cli.args[0] }}"
    php_version: "{{ cli.args[1] }}"
  roles:
    - valet-xdebug