---

package_channel: "testing"
distil_base_url: "https://distil.valet.sh"

package_manager_tmp_dir: "{{ base_dir }}/tmp"

package_base_dir: "{{ base_dir }}/{{ package.name }}/{{ package.version }}"
package_tmp_dir: "{{ package_base_dir }}/tmp"
package_dist_dir: "{{ package_base_dir }}/dist"
package_libs_dir: "{{ package_dist_dir }}/libs"

package_etc_dir: "{{ package_base_dir }}/etc"
package_run_dir: "{{ package_base_dir }}/run"
package_log_dir: "{{ package_base_dir }}/logs"

package_user: "{{ current_user }}"
package_group: "{{ current_group }}"