---

- name: "systemd | php5.6-fpm | started"
  systemd:
    name: "php5.6-fpm"
    state: started
  become: true

- name: "systemd | php5.6-fpm | stopped"
  systemd:
    name: "php5.6-fpm"
    state: stopped
  become: true

- name: "systemd | php5.6-fpm | restarted"
  systemd:
    name: "php5.6-fpm"
    state: restarted
  become: true

- name: "systemd | php5.6-fpm | reloaded"
  systemd:
    name: "php5.6-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.0-fpm | started"
  systemd:
    name: "php7.0-fpm"
    state: started
  become: true

- name: "systemd | php7.0-fpm | stopped"
  systemd:
    name: "php7.0-fpm"
    state: stopped
  become: true

- name: "systemd | php7.0-fpm | restarted"
  systemd:
    name: "php7.0-fpm"
    state: restarted
  become: true

- name: "systemd | php7.0-fpm | reloaded"
  systemd:
    name: "php7.0-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.1-fpm | started"
  systemd:
    name: "php7.1-fpm"
    state: started
  become: true

- name: "systemd | php7.1-fpm | stopped"
  systemd:
    name: "php7.1-fpm"
    state: stopped
  become: true

- name: "systemd | php7.1-fpm | restarted"
  systemd:
    name: "php7.1-fpm"
    state: restarted
  become: true

- name: "systemd | php7.1-fpm | reloaded"
  systemd:
    name: "php7.1-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.2-fpm | started"
  systemd:
    name: "php7.2-fpm"
    state: started
  become: true

- name: "systemd | php7.2-fpm | stopped"
  systemd:
    name: "php7.2-fpm"
    state: stopped
  become: true

- name: "systemd | php7.2-fpm | restarted"
  systemd:
    name: "php7.2-fpm"
    state: restarted
  become: true

- name: "systemd | php7.2-fpm | reloaded"
  systemd:
    name: "php7.2-fpm"
    state: reloaded
  become: true

- name: "systemd | php7.3-fpm | started"
  systemd:
    name: "php7.3-fpm"
    state: started
  become: true

- name: "systemd | php7.3-fpm | stopped"
  systemd:
    name: "php7.3-fpm"
    state: stopped
  become: true

- name: "systemd | php7.3-fpm | restarted"
  systemd:
    name: "php7.3-fpm"
    state: restarted
  become: true

- name: "systemd | php7.3-fpm | reloaded"
  systemd:
    name: "php7.3-fpm"
    state: reloaded
  become: true


- name: "systemd | php7.4-fpm | started"
  systemd:
    name: "php7.4-fpm"
    state: started
  become: true

- name: "systemd | php7.4-fpm | stopped"
  systemd:
    name: "php7.4-fpm"
    state: stopped
  become: true

- name: "systemd | php7.4-fpm | restarted"
  systemd:
    name: "php7.4-fpm"
    state: restarted
  become: true

- name: "systemd | php7.4-fpm | reloaded"
  systemd:
    name: "php7.4-fpm"
    state: reloaded
  become: true

- name: brew | vsh-php70 | restarted
  shell: brew services restart vsh-php70

- name: brew | vsh-php70 | stopped
  shell: brew services stop vsh-php70

- name: brew | vsh-php70 | started
  shell: brew services start vsh-php70

- name: brew | vsh-php71 | restarted
  shell: brew services restart vsh-php71

- name: brew | vsh-php71 | stopped
  shell: brew services stop vsh-php71

- name: brew | vsh-php71 | started
  shell: brew services start vsh-php71

- name: brew | vsh-php72 | restarted
  shell: brew services restart vsh-php72

- name: brew | vsh-php72 | stopped
  shell: brew services stop vsh-php72

- name: brew | vsh-php72 | started
  shell: brew services start vsh-php72

- name: brew | vsh-php73 | restarted
  shell: brew services restart vsh-php73

- name: brew | vsh-php73 | stopped
  shell: brew services stop vsh-php73

- name: brew | vsh-php73 | started
  shell: brew services start vsh-php73

- name: brew | vsh-php74 | restarted
  shell: brew services restart vsh-php74

- name: brew | vsh-php74 | stopped
  shell: brew services stop vsh-php74

- name: brew | vsh-php74 | started
  shell: brew services start vsh-php74
